#!/bin/bash

#install/configure real time clock
#20190203 km4ack
#script based on directions from the following web site
#https://thepihut.com/blogs/raspberry-pi-tutorials/17209332-adding-a-real-time-clock-to-your-raspberry-pi

clear;echo;echo

IC2ACTIVE=$(ls /dev/*i2c*)

if [ $IC2ACTIVE = "/dev/i2c-1" ]
then
echo "IC2 Sudah Aktif"
else 
clear;echo;echo
echo "Aktifkan dulu IC2 di menu interface "
echo "Raspberry Pi Configuration dan coba lagi"
exit 0
fi

clear;echo;echo
date
echo
read -p "Apakah waktu di atas sudah benar? y/n " ANS

if [ $ANS = 'y' ] || [ $ANS = 'Y' ]; then
echo "Mantap"
else
echo; echo "internet belum tersambung bro!"
echo "Atau pakai GPS bro!"; echo
exit 0
fi

sudo i2cdetect -y 1

echo;echo
read -p "Lihat ada angka 68 tidak?, bukan 69 bro! y/n " ANS1
echo
if [ $ANS1 = 'y' ] || [ $ANS1 = 'Y' ]; then
sudo modprobe rtc-ds1307
echo "ds1307 0x68" | sudo tee -a /sys/class/i2c-adapter/i2c-1/new_device
sudo hwclock -w
echo rtc-ds1307 | sudo tee -a /etc/modules

sudo sed -i 's/exit\ 0//' /etc/rc.local
echo "echo ds1307 0x68 > /sys/class/i2c-adapter/i2c-1/new_device" | sudo tee -a /etc/rc.local > /dev/null 2>&1
echo "sudo hwclock -s" | sudo tee -a /etc/rc.local > /dev/null 2>&1
echo "date" | sudo tee -a /etc/rc.local > /dev/null 2>&1
echo "exit 0" | sudo tee -a /etc/rc.local > /dev/null 2>&1
echo
echo "Jam sudah diinstal dan dikonfigurasi bro!"
echo "Periksa kembali ya bro sudah benar atau belum"
echo "ikutin langkahya dengan benar kalau tidak jelas ditanya bro!"
echo "kalau yakin berarti kamu sudah berhasil, doni1994"
else
echo "dicek jamnya bro sesuaikan sama daerah kamu bro"
echo "Jam sudah benar kalau belum"
echo "coba lagi!"
fi


